name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: drashna/qmk_firmware/.github/workflows/qmk_userspace_build.yml@qmk-userspace
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master
      keymap_name: tessachka

  publish:
    name: 'QMK Userspace Publish'
    uses: drashna/qmk_firmware/.github/workflows/qmk_userspace_publish.yml@qmk-userspace
    if: always() && !cancelled()
    needs: build
